application/models/__init__.py
__author__ = 'Daniil Nikulin'
__license__ = "Apache License 2.0"
__email__ = "danil.nikulin@gmail.com"
__date__ = "2018-01-06"
__app__ = "statswebapp"
__status__ = "Development"

"""
These imports enable us to make all defined models members of the models
module (as opposed to just their python files)
"""

from .user import *  # noqa
from .location import *

application/account/forms.py
from flask import url_for
from flask_wtf import FlaskForm
from wtforms import ValidationError
from wtforms.fields import (BooleanField, PasswordField, StringField,
                            SubmitField)
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length

from ..models import User


class LoginForm(FlaskForm):
    username = StringField(
        'Username', validators=[InputRequired(), Length(4, 64)])
    password = PasswordField('Password', validators=[InputRequired()])
    token = PasswordField('TOTP Token', validators=[InputRequired(), Length(6, 6)])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log in')


class RegistrationForm(FlaskForm):
    username = StringField(
        'Username', validators=[InputRequired(), Length(4, 64)])
    password = PasswordField(
        'Password',
        validators=[
            InputRequired(), EqualTo('password2', 'Passwords must match')
        ])
    password2 = PasswordField('Confirm password', validators=[InputRequired()])
    submit = SubmitField('Register')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already registered. (Did you mean to '
                                  '<a href="{}">log in</a> instead?)'
                                  .format(url_for('account.login')))


class RequestResetPasswordForm(FlaskForm):
    username = StringField(
        'Username', validators=[InputRequired(), Length(4, 64)])
    submit = SubmitField('Reset password')

    # We don't validate the email address so we don't confirm to attackers
    # that an account with the given email exists.


class ResetPasswordForm(FlaskForm):
    username = StringField(
        'Username', validators=[InputRequired(), Length(4, 64)])
    new_password = PasswordField(
        'New password',
        validators=[
            InputRequired(), EqualTo('new_password2', 'Passwords must match.')
        ])
    new_password2 = PasswordField(
        'Confirm new password', validators=[InputRequired()])
    submit = SubmitField('Reset password')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first() is None:
            raise ValidationError('Unknown email address.')


class CreatePasswordForm(FlaskForm):
    password = PasswordField(
        'Password',
        validators=[
            InputRequired(), EqualTo('password2', 'Passwords must match.')
        ])
    password2 = PasswordField(
        'Confirm new password', validators=[InputRequired()])
    submit = SubmitField('Set password')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Old password', validators=[InputRequired()])
    new_password = PasswordField(
        'New password',
        validators=[
            InputRequired(), EqualTo('new_password2', 'Passwords must match.')
        ])
    new_password2 = PasswordField(
        'Confirm new password', validators=[InputRequired()])
    submit = SubmitField('Update password')


class ChangeEmailForm(FlaskForm):
    email = EmailField(
        'New email', validators=[InputRequired(), Length(1, 64), Email()])
    password = PasswordField('Password', validators=[InputRequired()])
    submit = SubmitField('Update email')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

application/__init__.py
import os

from celery import Celery
from flask import Flask
from flask_mail import Mail
from flask_pymongo import PyMongo
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
# from flask_assets import Environment
from flask_wtf import CSRFProtect
from flask_compress import Compress
from flask_rq import RQ
from flask_bcrypt import Bcrypt
from pymongo.errors import ServerSelectionTimeoutError
from flask_redis import FlaskRedis

from config import config

# from .assets import app_css, app_js, vendor_css, vendor_js

basedir = os.path.abspath(os.path.dirname(__file__))

mail = Mail()
db = SQLAlchemy()
csrf = CSRFProtect()
compress = Compress()
mongo = PyMongo()
bcrypt = Bcrypt()
redis_store = FlaskRedis()
celery = Celery()

# Set up Flask-Login
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'account.login'


def create_app(config_name):
    if config_name == "development":
        print('THIS APP IS IN DEBUG MODE. YOU SHOULD NOT SEE THIS IN PRODUCTION.')
    app = Flask(__name__, static_url_path='/static')
    app.config.from_object(config[config_name])
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    # not using sqlalchemy event system, hence disabling it

    config[config_name].init_app(app)

    # Set up extensions
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    csrf.init_app(app)
    compress.init_app(app)
    redis_store.init_app(app, decode_responses=True)
    celery.config_from_object(app.config)
    celery.conf.ONCE = {
        'backend': 'celery_once.backends.Redis',
        'settings': {
            'url': config[config_name].CELERY_ONCE_BROKER_DB_URL,
            'default_timeout': 60 * 60
        }
    }

    # RQ(app)
    if not config_name == 'testing':
        try:
            mongo.init_app(app)
        except ServerSelectionTimeoutError as e:
            print("MongoDB Time Out")
            raise e
            pass
    bcrypt.init_app(app)

    # Register Jinja template functions
    from .utils import register_template_utils
    register_template_utils(app)

    # Set up asset pipeline
    # assets_env = Environment(app)
    # dirs = ['assets/styles', 'assets/scripts']
    # for path in dirs:
    #     assets_env.append_path(os.path.join(basedir, path))
    # assets_env.url_expire = True
    #
    # assets_env.register('app_css', app_css)
    # assets_env.register('app_js', app_js)
    # assets_env.register('vendor_css', vendor_css)
    # assets_env.register('vendor_js', vendor_js)

    # Configure SSL if platform supports it
    if not app.debug and not app.testing and not app.config['SSL_DISABLE']:
        from flask.ext.sslify import SSLify
        SSLify(app)

    # Create app blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .dashboard import dashboard as dashboard_blueprint
    app.register_blueprint(dashboard_blueprint, url_prefix='/dashboard')

    from .account import account as account_blueprint
    app.register_blueprint(account_blueprint, url_prefix='/account')

    from .ajax_requests import ajax_requests as ajax_requests_blueprint
    app.register_blueprint(ajax_requests_blueprint, url_prefix='/ajax_requests')

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .twilio_responses import twilio_responses as twilio_responses_blueprint
    app.register_blueprint(twilio_responses_blueprint, url_prefix='/twilio_responses')

    # from .admin import admin as admin_blueprint
    # app.register_blueprint(admin_blueprint, url_prefix='/admin')
    #
    # for name in find_modules('application'):
    #     mod = import_string(name)
    #     if hasattr(mod, 'bp'):
    #         app.register_blueprint(mod.bp)
    # return None
    return app

application/account/__init__.py
__author__ = 'Daniil Nikulin'
__copyright__ = "Copyright 2017"
__license__ = "Apache License 2.0"
__version__ = "1.0"
__maintainer__ = "Daniil Nikulin"
__email__ = "danil.nikulin@gmail.com"
__status__ = "Development"

from flask import Blueprint

account = Blueprint('account', __name__)

from . import views

application/account/views.py
from datetime import datetime

from application import db
from application.main_logic.custom_logging import save_accessing, save_action
from application.main_logic.nav_info import HeaderNavbarInfo, SidebarInfo

__author__ = 'Daniil Nikulin'
__license__ = "Apache License 2.0"
__email__ = "danil.nikulin@gmail.com"
__date__ = "2018-01-10"
__app__ = "statswebapp"
__status__ = "Development"
#####
# IMPORTS
#####
from flask import flash, redirect, render_template, request, url_for, session
from flask_login import (current_user, login_required, login_user,
                         logout_user)

from . import account
from ..models import User
from .forms import (ChangeEmailForm, ChangePasswordForm, CreatePasswordForm,
                    LoginForm, RegistrationForm, RequestResetPasswordForm,
                    ResetPasswordForm)


@account.before_request
def before_request():
    save_accessing(current_user, request)
    session.permanent = True


@account.route('/login', methods=['GET', 'POST'])
def login():
    """Log in an existing user."""
    if current_user.is_authenticated:
        # if user is logged in we get out of here
        return redirect(url_for('dashboard.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.password_hash is not None and \
                user.verify_password(form.password.data) \
                and user.verify_totp(form.token.data):
            login_user(user, form.remember_me.data)
            flash('You are now logged in. Welcome back!', 'success')
            save_action(current_user, request, " Successfully  authenticated")
            return redirect(request.args.get('next') or url_for('dashboard.index'))
        else:
            save_action(current_user, request, "Inserted wrong username or password")
            flash('Invalid username,password or token.', 'error')
            flash('Invalid username,password or token.', 'form-error')
    return render_template('account/login.html', form=form, header_nav_info=HeaderNavbarInfo(),
                           sidebar_info=SidebarInfo())


@account.route('/logout')
@login_required
def logout():
    logout_user()
    save_action(current_user, request, "Logged out")
    flash('You have been logged out.', 'info')
    return redirect(url_for('main.index'))


@account.route('/manage', methods=['GET', 'POST'])
@account.route('/manage/info', methods=['GET', 'POST'])
@login_required
def manage():
    """Display a user's account information."""
    return render_template('account/manage.html', user=current_user, form=None, header_nav_info=HeaderNavbarInfo(),
                           sidebar_info=SidebarInfo())


@account.route('/manage/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    """Change an existing user's password."""
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.new_password.data
            db.session.add(current_user)
            db.session.commit()
            flash('Your password has been updated.', 'success')
            flash('Your password has been updated.', 'form-success')
            save_action(current_user, request, "Changed Password")
            return redirect(url_for('main.index'))
        else:
            save_action(current_user, request, "Inserted wrong password while trying to change password")
            flash('Original password is invalid.', 'error')
            flash('Original password is invalid.', 'form-error')
    return render_template('account/change_password.html', form=form, user=current_user,
                           header_nav_info=HeaderNavbarInfo(),
                           sidebar_info=SidebarInfo())

application/admin/__init__.py
__author__ = 'Daniil Nikulin'
__copyright__ = "Copyright 2017"
__license__ = "Apache License 2.0"
__version__ = "1.0"
__maintainer__ = "Daniil Nikulin"
__email__ = "danil.nikulin@gmail.com"
__status__ = "Development"

from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

application/ajax_requests/__init__.py
__author__ = 'Daniil Nikulin'
__license__ = "Apache License 2.0"
__email__ = "danil.nikulin@gmail.com"
__date__ = "2018-01-16"
__app__ = "statswebapp"
__status__ = "Development"

from flask import Blueprint

ajax_requests = Blueprint('ajax_requests', __name__)

from . import views

application/ajax_requests/views.py
from application.main_logic.ajax_responses import get_status_panel_ajax
from application.main_logic.custom_logging import save_action
from application.main_logic.functions import is_panel_exist
from application.main_logic.nav_info import HeaderNavbarInfo
from application.models import LocationFieldPanel

__author__ = 'Daniil Nikulin'
__license__ = "Apache License 2.0"
__email__ = "danil.nikulin@gmail.com"
__date__ = "2018-01-10"
__app__ = "statswebapp"
__status__ = "Development"
from flask import flash, redirect, render_template, request, url_for, abort, jsonify
from flask_login import (current_user, login_required, login_user,
                         logout_user)

from . import ajax_requests
from application import db


@login_required
@ajax_requests.route('/status_table/<string:pool_name>', methods=['GET'])
def status_table(pool_name):
    """Log in an existing user."""
    if not is_panel_exist(panel_name=pool_name):
        abort(404)
    else:
        response = get_status_panel_ajax(pool_name)

        return jsonify(response)


@login_required
@ajax_requests.route('/change_location', methods=['POST', 'GET'])
def change_location():
    """Save location"""
    try:
        hostname = str(request.form.get('hostname'))
        location = str(request.form.get('location'))
        loc = LocationFieldPanel(
            hostname=hostname,
            number=location
        )
        if LocationFieldPanel.query.filter_by(hostname=hostname).first() is None \
                and LocationFieldPanel.query.filter_by(number=location).first() is None:
            # session.query(User).filter_by(id=123).update({"name": u"Bob Marley"})
            db.session.add(loc)
            db.session.commit()
            save_action(current_user, request, "Added location: {} for rig: {} ".format(loc.number, loc.hostname))
        else:
            loc = LocationFieldPanel.query.filter_by(hostname=hostname).first()
            if LocationFieldPanel.query.filter_by(number=location).first() is None:
                loc.hostname = hostname
                loc.number = location
                db.session.add(loc)
                db.session.commit()
                save_action(current_user, request, "Added location: {} for rig: {} ".format(loc.number, loc.hostname))
            else:
                loc = LocationFieldPanel.query.filter_by(number=location).first()
                loc.hostname = hostname
                loc.number = location
                db.session.add(loc)
                db.session.commit()
                save_action(current_user, request, "Changed location: {} for rig: {} ".format(loc.number, loc.hostname))
    except Exception as e:
        print(e)
        db.session.rollback()
        abort(500)
        save_action(current_user, request, "Failed to add/change location")
        raise

    return "200"

application/celery_tasks/__init__.py
__author__ = 'Daniil Nikulin'
__license__ = "Apache License 2.0"
__email__ = "danil.nikulin@gmail.com"
__date__ = "2018-01-17"
__app__ = "statswebapp"
__status__ = "Development"

application/dashboard/__init__.py
__author__ = 'Daniil Nikulin'
__copyright__ = "Copyright 2017"
__license__ = "Apache License 2.0"
__version__ = "1.0"
__maintainer__ = "Daniil Nikulin"
__email__ = "danil.nikulin@gmail.com"
__status__ = "Development"

from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

from . import views

application/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

application/main/views.py
from flask import render_template, request, redirect, url_for, session
from flask_login import current_user

from application.main_logic.custom_logging import save_accessing
from application.main_logic.nav_info import SidebarInfo, HeaderNavbarInfo
from . import main


@main.before_request
def before_request():
    save_accessing(current_user, request)
    session.permanent = True


@main.route('/')
def index():
    if current_user.is_authenticated:
        # if user is logged in we get out of here
        return redirect(url_for('dashboard.index'))
    return render_template('main/index.html', sidebar_info=SidebarInfo(), header_nav_info=HeaderNavbarInfo())

application/main_logic/__init__.py
__author__ = 'Daniil Nikulin'
__license__ = "Apache License 2.0"
__email__ = "danil.nikulin@gmail.com"
__date__ = "2018-01-09"
__app__ = "statswebapp"
__status__ = "Development"

application/twilio_responses/__init__.py
from application import csrf

__author__ = 'Daniil Nikulin'
__license__ = "Apache License 2.0"
__email__ = "danil.nikulin@gmail.com"
__date__ = "2018-02-21"
__app__ = "statswebapp"
__status__ = "Development"


from flask import Blueprint

twilio_responses = Blueprint('twilio_responses', __name__)
csrf.exempt(twilio_responses)

from . import views

application/templates/partials/nav/control_sidebar.html
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            {#<h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->#}
        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

application/templates/partials/nav/header_navbar.html
<!-- Header Navbar -->
<nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
    </a>
    {#<ul class="nav navbar-nav hidden-xs" style="text-align: center; font-weight: bold;">
        <li><a>ETH/USD {{ header_nav_info.eth_usd }}</a></li>
        <li><a>ETH/EUR {{ header_nav_info.eth_eur }}</a></li>
    </ul>#}
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            {% if current_user.is_authenticated %}
                {#<!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">12</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 12 messages</li>
                        <li>
                            <!-- inner menu: contains the messages -->
                            <ul class="menu">
                                <li><!-- start message -->
                                    <a href="#">
                                        <div class="pull-left">
                                            <!-- User Image -->
                                            <img src="{{ url_for('static',filename= 'dist/img/avatar04.png') }}"
                                                 class="img-circle" alt="User Image">
                                        </div>
                                        <!-- Message title and timestamp -->
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <!-- The message -->
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                                <!-- end message -->
                            </ul>
                            <!-- /.menu -->
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                <!-- /.messages-menu -->
                <!-- Attack Menu -->#}
                {% if header_nav_info.num_of_rigs_under_attack %}<li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="font-size: large">
                        <i class="fa fa-bug"></i>
                        <span class="label label-danger">Attack</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">Attack detected</li>
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li><!-- start notification -->
                                    <a href="#">
                                        <i class="fa fa-bug text-red"></i> Number of rigs under attack {{ header_nav_info.num_of_rigs_under_attack }}
                                    </a>
                                </li>
                                <!-- end notification -->
                            </ul>
                        </li>
                        {#<li class="footer"><a href="#">View all</a></li>#}
                    </ul>
                </li>{% endif %}
                <!-- Tasks Menu -->
                {#<li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <li><!-- Task item -->
                                    <a href="#">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <!-- The progress bar -->
                                        <div class="progress xs">
                                            <!-- Change the css width attribute to simulate progress -->
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%"
                                                 role="progressbar"
                                                 aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <!-- end task item -->
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>#}
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ url_for('static',filename= 'dist/img/avatar04.png') }}" class="user-image"
                             alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ current_user.username }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ url_for('static',filename= 'dist/img/avatar04.png') }}" class="img-circle"
                                 alt="User Image">
                            <p>
                                {{ current_user.username }} - {{ current_user.role.name }}
                                {#<small>Member since Nov. 2012</small>#}
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            {#<div class="row">
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Followers</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Sales</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Friends</a>
                                    </div>
                                </div>
                                <!-- /.row -->#}
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{{ url_for("account.manage") }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url_for('account.logout') }}" class="btn btn-default btn-flat">Sign
                                    out</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>
            {% else %}
                <ul class="nav navbar-nav navbar-left">
                    {#<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>#}
                    <li><a href="{{ url_for('account.login') }}"><span class="glyphicon glyphicon-log-in"></span>
                        Login</a></li>
                </ul>
            {% endif %}

        </ul>
    </div>
</nav>